[project]
name = "Modulo-Common"
version = "0.3.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Theo Sementa", email = "theosementa@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.84.0",
    "protobuf>=7.36.2",
    "sqlalchemy>=2.1.1",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "grpcio-tools>=1.84.0",
]
