# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modulo_common/grpc/auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'modulo_common/grpc/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmodulo_common/grpc/auth.proto\x12\x0emodulo.auth.v1\"g\n\rAppleUserBody\x12\x15\n\ridentityToken\x18\x01 \x01(\t\x12\x19\n\x11\x61uthorizationCode\x18\x02 \x01(\t\x12\x16\n\tfirstName\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_firstName\"h\n\x11\x41ppleUserResponse\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x0cisNewAccount\x18\x02 \x01(\x08\x12-\n\x06tokens\x18\x03 \x01(\x0b\x32\x1d.modulo.auth.v1.TokenResponse\"(\n\x10RefreshTokenBody\x12\x14\n\x0crefreshToken\x18\x01 \x01(\t\":\n\rTokenResponse\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t2\xb7\x01\n\x0b\x41uthService\x12U\n\x0fSignInWithApple\x12\x1d.modulo.auth.v1.AppleUserBody\x1a!.modulo.auth.v1.AppleUserResponse\"\x00\x12Q\n\x0cRefreshToken\x12 .modulo.auth.v1.RefreshTokenBody\x1a\x1d.modulo.auth.v1.TokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modulo_common.grpc.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLEUSERBODY']._serialized_start=49
  _globals['_APPLEUSERBODY']._serialized_end=152
  _globals['_APPLEUSERRESPONSE']._serialized_start=154
  _globals['_APPLEUSERRESPONSE']._serialized_end=258
  _globals['_REFRESHTOKENBODY']._serialized_start=260
  _globals['_REFRESHTOKENBODY']._serialized_end=300
  _globals['_TOKENRESPONSE']._serialized_start=302
  _globals['_TOKENRESPONSE']._serialized_end=360
  _globals['_AUTHSERVICE']._serialized_start=363
  _globals['_AUTHSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
