# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from modulo_common.grpc import auth_pb2 as modulo__common_dot_grpc_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in modulo_common/grpc/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignInWithApple = channel.unary_unary(
                '/modulo.auth.v1.AuthService/SignInWithApple',
                request_serializer=modulo__common_dot_grpc_dot_auth__pb2.AppleUserBody.SerializeToString,
                response_deserializer=modulo__common_dot_grpc_dot_auth__pb2.AppleUserResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/modulo.auth.v1.AuthService/RefreshToken',
                request_serializer=modulo__common_dot_grpc_dot_auth__pb2.RefreshTokenBody.SerializeToString,
                response_deserializer=modulo__common_dot_grpc_dot_auth__pb2.TokenResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SignInWithApple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignInWithApple': grpc.unary_unary_rpc_method_handler(
                    servicer.SignInWithApple,
                    request_deserializer=modulo__common_dot_grpc_dot_auth__pb2.AppleUserBody.FromString,
                    response_serializer=modulo__common_dot_grpc_dot_auth__pb2.AppleUserResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=modulo__common_dot_grpc_dot_auth__pb2.RefreshTokenBody.FromString,
                    response_serializer=modulo__common_dot_grpc_dot_auth__pb2.TokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modulo.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modulo.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignInWithApple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modulo.auth.v1.AuthService/SignInWithApple',
            modulo__common_dot_grpc_dot_auth__pb2.AppleUserBody.SerializeToString,
            modulo__common_dot_grpc_dot_auth__pb2.AppleUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modulo.auth.v1.AuthService/RefreshToken',
            modulo__common_dot_grpc_dot_auth__pb2.RefreshTokenBody.SerializeToString,
            modulo__common_dot_grpc_dot_auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
