# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modulo_common/grpc/users.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'modulo_common/grpc/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emodulo_common/grpc/users.proto\x12\x0fmodulo.users.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n\x08UserBody\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x16\n\tfirstName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12/\n\x08provider\x18\x03 \x01(\x0e\x32\x1d.modulo.users.v1.ProviderType\x12\x12\n\nproviderId\x18\x04 \x01(\tB\x0c\n\n_firstName\"\xc2\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\tfirstName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12/\n\x08provider\x18\x04 \x01(\x0e\x32\x1d.modulo.users.v1.ProviderType\x12-\n\tcreatedAt\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tisNewUser\x18\x06 \x01(\x08\x42\x0c\n\n_firstName*{\n\x0cProviderType\x12\x1d\n\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13PROVIDER_TYPE_APPLE\x10\x01\x12\x18\n\x14PROVIDER_TYPE_GOOGLE\x10\x02\x12\x19\n\x15PROVIDER_TYPE_CLASSIC\x10\x03\x32X\n\x0bUserService\x12I\n\x0bGetOrCreate\x12\x19.modulo.users.v1.UserBody\x1a\x1d.modulo.users.v1.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modulo_common.grpc.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVIDERTYPE']._serialized_start=416
  _globals['_PROVIDERTYPE']._serialized_end=539
  _globals['_USERBODY']._serialized_start=85
  _globals['_USERBODY']._serialized_end=217
  _globals['_USERRESPONSE']._serialized_start=220
  _globals['_USERRESPONSE']._serialized_end=414
  _globals['_USERSERVICE']._serialized_start=541
  _globals['_USERSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
